name: CI/CD Server Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy_server_prod:
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'server')
    runs-on: ubuntu-latest
    name: Deploy Server to Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'

      - name: Install dependencies for server
        working-directory: ./server
        run: npm install

      - name: Deploy and run the application in prod mode
        working-directory: ./server
        run: npm run prod

      - name: Deploy to Railway
        working-directory: ./server
        run: railway up --environment prod
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}